apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "a1j/JVaIrJIKN/IvjqCa0TQiKXfErZZgdRSVgBEO5SYbqAJsgxl/zjWReQF99pZD\nuJqek2B1xR48NH7JJCAXe/FWOiMibguE9+7bLa1zpSnhDW3tNP4YaxragqYF4dhd\nRYY04S0DiH0MZ921zwpw+x8HG02ru0SbTNtaVzUglO4="
